### ISSUE TITLE
The plugin makes the IDE very slow if editing kotlin code in a project contains java and kotlin 

### ISSUE THREAD

**Issue by danny-su** [manifold-systems/manifold-ij#12]
The plugin makes the IDE very slow if editing kotlin code in a project contains java and kotlin.

**Comment by danny-su** [comment]
especially, when the kotlin.String type shows in the list of auto-completion,  the IDE will got stuck for a few seconds even more.

**Comment by rsmckinney** [comment]
I am not seeing this any longer. Do you still experience this?
