### ISSUE TITLE
Regression: Extensions Not Recognized Until Project Is Reopened

### ISSUE THREAD

**Issue by gudenau** [manifold-systems/manifold-ij#16]
Like issue #14 the extensions that I create are not recognized until I reopen my project in Idea. It only appears to affect Gradle modules that do not yet have an extension in them, as I found it while creating the project that I initially found manifold-systems/manifold#459. It happened on the original project and the minimal test case as I was writing them.

It appears as though the reproduction steps are the following:
1. Create extension class in a project that did not have one
2. Plugin can not see it
3. Reload Idea project
4. Plugin can see it
5. Create new extension in a project that had it
6. Plugin can see it

**Comment by rsmckinney** [comment]
Fixed a while back.
