### ISSUE TITLE
no code highlighting in string templates

### ISSUE THREAD

**Issue by rhysdh540** [manifold-systems/manifold-ij#17]
code that is usually colored is not if it is inside a string template (such as `"$foo"`). Here's an example:
![image](https://github.com/manifold-systems/manifold-ij/assets/98863820/d6b252b4-887c-4d2d-99c4-ddc38d545e6d)

I'm using version 2023.2.1 of IJ, 2023.1.19 of the plugin, 2023.1.22 of manifold-strings, and gerry themes.

**Comment by rhysdh540** [comment]
also somewhat unrelated but it would be cool to have an inspection that converted string templates to string concatenation and vice versa (like IJ does with `.formatted()` and StringBuilders.

**Comment by CC007** [comment]
It would be nice to have a Manifold section in Settings -> Editor -> Code Style, where you could configure several things like the color of fields from manifold-props, extension methods from manifold-ext and interpolated variables from manifold-strings, 

For instance it's the default in Kotlin to color extension methods differently than normal methods. That would also be nice in Manifold.

**Comment by rsmckinney** [comment]
@CC007 Please file a separate issue for this in the manifold project. Thanks!

**Comment by rsmckinney** [comment]
@rhysdh540 Please file a separate issue for the inspection. Thanks!

**Comment by rsmckinney** [comment]
@rhysdh540 Regarding the highlighting, there is highlighting, however as you point out it doesn't necessarily use the colors you scheme you have configured. On my end the manifold plugin implements the necessary APIs to single out the template expressions in the string so IntelliJ can highlight them, provide code completion, etc. It appears IJ somehow does not apply the configured scheme in this case, so I'm going to pass this over to them.
