### ISSUE TITLE
String interpolation doesn't work with manifold-ij

### ISSUE THREAD

**Issue by ice1000** [manifold-systems/manifold-ij#29]
![image](https://github.com/manifold-systems/manifold-ij/assets/16398479/72e3c087-317f-4399-9bc3-44bf34fd3569)

It doesn't work! Env same as #27 but with manifold-ij updated

**Comment by ice1000** [comment]
> Sorry about that,fix coming in tomorrows plugin release.

No worries! Btw, it looks like records with `@link` are still unsupported (https://github.com/manifold-systems/manifold/issues/587), I tried to use gradle to compile, and it gives me errors about methods being unimplemented. Should I file an issue, or should I wait for a release?

**Comment by ice1000** [comment]
> The plugin release scheduled for Monday was delayed due to a couple of other issues that have surfaced.

In the issue, you mentioned it already works, but the intellij plugin needs to be updated. However, compilation also does not work for me.

Do you need MWE? I'll try to come up with one later

**Comment by rsmckinney** [comment]
> compilation also does not work

It should work... What happens if you test a simple example?
```java
  System.out.println(new MyRecord("hi").charAt(0));

  record MyRecord(@link CharSequence cs) implements CharSequence {
  }
```

**Comment by ice1000** [comment]
I'll try to figure out later. I'm in a meeting right now.

**Comment by ice1000** [comment]
Error production: https://github.com/ice1k/manifold-java-bug-report/actions/runs/9089055436/job/24979607037#step:4:50

Code that produces the error: https://github.com/ice1k/manifold-java-bug-report/blob/main/src/main/java/Main.java#L3-L9

**Comment by ice1000** [comment]
I've updated the code to use `CharSequence` and it still reproduces the error

**Comment by rsmckinney** [comment]
It all works for me. Is your project available or can your provide your build files? I just need a way to reproduce your environment so I can reproduce this. If you have a simple sample project that would be even better.  Thanks.

**Comment by ice1000** [comment]
> It all works for me. Is your project available or can your provide your build files? I just need a way to reproduce your environment so I can reproduce this. If you have a simple sample project that would be even better.  Thanks.

The links above belong to a minimal gradle project, you can checkout and reproduce the error by using `./gradlew classes`

**Comment by ice1000** [comment]
The code is here: https://github.com/ice1k/manifold-java-bug-report

**Comment by ice1000** [comment]
The link I gave you earlier is the execution log of a continuous-integration system that is nowadays very popular called GitHub Actions. The code that used to generate that log can be found in the `.github/workflows` folder of the repository.

**Comment by rsmckinney** [comment]
Your gradle.build.kts file is missing the vital "-Xplugin:Manifold" compiler argument. See [setup docs](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-delegation#gradle).

![image](https://github.com/manifold-systems/manifold-ij/assets/588843/25a8d525-5038-4317-9cde-890db23a725c)

**Comment by ice1000** [comment]
> Your gradle.build.kts file is missing the vital "-Xplugin:Manifold" compiler argument. See [setup docs](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-delegation#gradle).
> 
> ![image](https://private-user-images.githubusercontent.com/588843/331043016-25a8d525-5038-4317-9cde-890db23a725c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mzg5NjgsIm5iZiI6MTcxNTgzODY2OCwicGF0aCI6Ii81ODg4NDMvMzMxMDQzMDE2LTI1YThkNTI1LTUwMzgtNDMxNy05Y2RlLTg5MGRiMjNhNzI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwNTUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmUzZWMyMTU1M2U5YjM3YjcyYzY4NGZkNDhhMDEzN2E4MGM2OWJjNTlkZmM2ZmFlZDI2ZTNiOTllYmI2Y2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8usHzz6hD-7zCKc-2M186qw-oLYhF-Cf3NTSTw3OBoA)

!!!!!!!!!!!!! Thank you!!!
