### ISSUE TITLE
Illegal string escape

### ISSUE THREAD

**Issue by ice1000** [manifold-systems/manifold-ij#32]
Using https://github.com/manifold-systems/manifold-ij/issues/31#issuecomment-2116860834, I get
![image](https://github.com/manifold-systems/manifold-ij/assets/16398479/d9964d50-c541-4b69-bd9d-c970572b3633)

in a random project

**Comment by ice1000** [comment]
IntelliJ IDEA 2024.2 EAP (Ultimate Edition)
Build #IU-242.10180.25, built on May 15, 2024
Licensed to IntelliJ IDEA EAP user: Yinsen Zhang
Expiration date: June 14, 2024
Runtime version: 21.0.3+13-b446.1 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2010M
Cores: 20
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  org.canonical.intellij (1.0)
  PsiViewer (242.4697)
  manifold.ij (2024.1.2)
  org.jetbrains.idea.grammar (2022.3.2)
  org.ice1000.kala (0.9)
  org.aya.intellij (0.0.1-SNAPSHOT)
  com.jetbrains.darkPurpleTheme (1.3)
  com.jetbrains.space (242.10180.28)
  fuck.idea.jpms (SNAPSHOT)
  com.perl5 (242.5944)
Kotlin: 242.10180.25-IJ

**Comment by rsmckinney** [comment]
Here you just need to refresh your maven/gradle build.

**Comment by ice1000** [comment]
https://github.com/manifold-systems/manifold-ij/assets/16398479/2c8b0268-a23c-40b2-8631-953679abbd88

**Comment by ice1000** [comment]
Still doesn't work :(

**Comment by rsmckinney** [comment]
Are you using JDK 21 _Preview_ as your IJ JDK?

**Comment by ice1000** [comment]
> Are you using JDK 21 _Preview_ as your IJ JDK?

Yes

**Comment by ice1000** [comment]
Of course. String template is a preview feature

**Comment by rsmckinney** [comment]
I can't reproduce the error. A sample project or build file that produces this error would help me find the problem.  Thanks.
