### ISSUE TITLE
Add option to suppress "outdated Manifold dependencies" popup?

### ISSUE THREAD

**Issue by DaMatrix** [manifold-systems/manifold-ij#42]
The Manifold plugin gives a popup warning "Some of your project's Manifold dependencies are out of date..." every time a project is opened and on every Gradle refresh (which occurs often when switching branches). I do not want to be on the bleeding edge all the time, especially not on a stable branch whose dependency versions are pinned. It would be nice to have an option to disable this popup, globally or per-project.

![image](https://github.com/user-attachments/assets/a43b3a4d-4bc8-4cc3-979a-baf5bed42770)

**Comment by rsmckinney** [comment]
Feature available with latest plugin release.

`File | Settings | Manifold | Suppress Manifold version check`

>Note, although the IJ plugin aims for backward compatibility, using this feature may result in IDE errors/inconsistencies if the version of manifold the IJ plugin uses is newer than the one the project uses. It's unlikely, but possible for this to happen in a future release. Caveat emptor.

**Comment by DaMatrix** [comment]
Awesome, thanks!
