### ISSUE TITLE
Issue with manifold-colections inspection

### ISSUE THREAD

**Issue by LelouBil** [manifold-systems/manifold-ij#5]
Hello,
I'm currently using IntelliJ 2018.2 and just started using manifold.
I created a new maven project and added manifold-all to my pom.

Everything went fine until I started using collections.

in the following method, getKey and getValue are in red
`protected Map<String, String> getStupidExampleThatCompilesButShowsRedOnEditor(Map<String, CompletableFuture<String>> map) {
        Collection<CompletableFuture<String>> values = map.values();
        CompletableFuture[] facetRequests = values.toArray(new CompletableFuture[values.size()]);

        CompletableFuture<Map<String, String>> facetMap =  CompletableFuture.allOf(facetRequests).thenApply(v ->
                map.entrySet().stream()
                        .collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().join())) // getKey and getValue are red
        );
        return facetMap.join();
    }`

I found out that this happens only with manifold-collections.

(edit) and this is not a problem with manifold itelf, since the code compiles just fine with mvn compile

**Comment by rsmckinney** [comment]
Your example appears to be a general bug within IntelliJ and not Manifold.  I used your example in IJ without the Manifold plugin and see the same compile errors around the getKey() / getValiue() calls.
