### ISSUE TITLE
jdk included in the repository

### ISSUE THREAD

**Issue by migroskub** [manifold-systems/manifold-ij#8]
I'm looking at the code and I've seen a pretty odd thing - jdk 1.8 is pushed to this very git repository. Any reason to do so?

**Comment by rsmckinney** [comment]
For testing. The plugin derives a special fixture from the IJ one which requires a real jdk. I don’t like it, there’s probably a better way.

**Comment by rsmckinney** [comment]
See the AbstractManifoldCodeInsightTest base class. It extends the SomewhatLightCodeInsightFixtureTestCase class, which in a roundabout way requires a physical JDK to be be present. I haven't looked at this code in a long time, but as I remember I couldn't find an easier way to test manifold features without having to derive a hybrid "somewhat light" test fixture. There probably is a better way, I just don't know what that is.
